name: Issue Parser

on:
  issue_comment:
  
jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
        uses: actions/checkout@v3

      run: |
        echo 'This is an issue comment'
